project:
  type: website
  output-dir: docs

website:
  title: "Tobias Dienlin"
  site-url: https://tdienlin.github.io
  favicon: images/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: https://drive.switch.ch/index.php/s/UsTkjl3VqNpECsc
        text: CV
        target: _blank
      - href: contact.qmd
        text: Contact
  description: "Website of Tobias Dienlin, Professor for Media Psychology and Methods, University of Zurich. Research interest: Media Effects, Well-Being, Privacy, Open Science."

format:
  html:
    theme: cosmo
    css: style.css
    max-width: 800px